export const REQUEST_SEARCH_RESPONSE = 'REQUEST_SEARCH_RESPONSE'
export const RECEIVE_INITIAL_SEARCH_RESPONSE = 'RECEIVE_INITIAL_SEARCH_RESPONSE'
export const RECEIVE_ENTIRE_SEARCH_RESPONSE = 'RECEIVE_ENTIRE_SEARCH_RESPONSE'

export const REQUEST_SEARCH_RESPONSE_SIMPLE = 'REQUEST_SEARCH_RESPONSE_SIMPLE'
export const RECEIVE_INITIAL_SEARCH_RESPONSE_SIMPLE = 'RECEIVE_INITIAL_SEARCH_RESPONSE_SIMPLE'
export const RECEIVE_ENTIRE_SEARCH_RESPONSE_SIMPLE = 'RECEIVE_ENTIRE_SEARCH_RESPONSE_SIMPLE'

export const REQUESTED_API = 'REQUESTED_API'
export const RECEIVED_API = 'RECEIVED_API'
export const RECEIVED_ARTICLES = 'RECEIVED_ARTICLES'
